#!/bin/sh

sudo rm -rf /usr/lib/sticky
sudo cp -R etc /
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

sticky

#Fix Bugs

Look through the `GitHub issues for bugs <https://github.com/pytest-dev/pytest/labels/type:%20bug>`_.
See also the `"status: easy" issues <https://github.com/pytest-dev/pytest/labels/status%3A%20easy>`_
that are friendly to new contributors.

:ref:`Talk <contact>` to developers to find out how you can fix specific bugs. To indicate that you are going
to work on a particular issue, add a comment to that effect on the specific issue.
